# Generated by Django 6.0.2 on 2026-02-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('area_sqm', models.IntegerField()),
                ('solar_irradiance_kwh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grid_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope_degrees', models.DecimalField(decimal_places=2, max_digits=4)),
                ('road_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation_m', models.IntegerField()),
                ('land_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_irradiance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grid_distance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slope_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('infrastructure_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_suitability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parameters_snapshot', models.JSONField()),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='sites.site')),
            ],
            options={
                'ordering': ['-analysis_timestamp'],
            },
        ),
    ]
